# Generated by Django 3.0.3 on 2020-03-11 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EQT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_No', models.CharField(max_length=20)),
                ('E_Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_No', models.CharField(max_length=15)),
                ('M_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PJT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_No', models.CharField(max_length=20)),
                ('P_Name', models.CharField(max_length=50)),
                ('P_Country', models.CharField(max_length=20)),
                ('P_Client', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['P_No'],
            },
        ),
        migrations.CreateModel(
            name='PDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_Name', models.CharField(max_length=40)),
                ('PD_Fluid', models.CharField(max_length=20)),
                ('PD_Head', models.IntegerField()),
                ('PD_Dens', models.IntegerField()),
                ('PD_NPSH', models.IntegerField()),
                ('E_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mds02.EQT')),
                ('M_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mds02.MR')),
                ('P_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mds02.PJT')),
            ],
        ),
        migrations.AddField(
            model_name='mr',
            name='P_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mds02.PJT'),
        ),
        migrations.CreateModel(
            name='MDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_Name', models.CharField(max_length=40)),
                ('MD_Type', models.CharField(max_length=20)),
                ('MD_Seal', models.CharField(max_length=20)),
                ('MD_Matl', models.CharField(max_length=20)),
                ('E_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mds02.EQT')),
                ('M_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mds02.MR')),
                ('P_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mds02.PJT')),
            ],
        ),
        migrations.AddField(
            model_name='eqt',
            name='M_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mds02.MR'),
        ),
        migrations.AddField(
            model_name='eqt',
            name='P_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mds02.PJT'),
        ),
    ]
