# Generated by Django 3.0.3 on 2020-03-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mds02', '0002_auto_20200311_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqt',
            name='E_Name',
            field=models.CharField(max_length=40, verbose_name='EQT_Name'),
        ),
        migrations.AlterField(
            model_name='mds',
            name='E_Name',
            field=models.CharField(max_length=40, verbose_name='EQT_Name'),
        ),
        migrations.AlterField(
            model_name='mds',
            name='MD_Matl',
            field=models.CharField(max_length=20, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='mds',
            name='MD_Seal',
            field=models.CharField(max_length=20, verbose_name='Seal'),
        ),
        migrations.AlterField(
            model_name='mds',
            name='MD_Type',
            field=models.CharField(max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='mr',
            name='M_Name',
            field=models.CharField(max_length=50, verbose_name='MR_Name'),
        ),
        migrations.AlterField(
            model_name='mr',
            name='M_No',
            field=models.CharField(max_length=15, verbose_name='MR_No'),
        ),
        migrations.AlterField(
            model_name='pjt',
            name='P_Client',
            field=models.CharField(max_length=30, verbose_name='PJT_Client'),
        ),
        migrations.AlterField(
            model_name='pjt',
            name='P_Country',
            field=models.CharField(max_length=20, verbose_name='PJT_Country'),
        ),
        migrations.AlterField(
            model_name='pjt',
            name='P_Name',
            field=models.CharField(max_length=50, verbose_name='PJT_Name'),
        ),
        migrations.AlterField(
            model_name='pjt',
            name='P_No',
            field=models.CharField(max_length=20, verbose_name='PJT_No'),
        ),
    ]
