# Generated by Django 3.0.3 on 2020-03-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mds02', '0004_auto_20200311_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqt',
            name='E_Name',
            field=models.CharField(max_length=40, verbose_name='EQT_No'),
        ),
    ]
