# Generated by Django 3.0.3 on 2020-03-11 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mds02', '0005_auto_20200311_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='mds',
            name='MDS_Note',
            field=models.TextField(default=None, verbose_name='MDS_Note'),
        ),
        migrations.AddField(
            model_name='mr',
            name='M_Remark',
            field=models.TextField(default=None, verbose_name='MR_Note'),
        ),
        migrations.AddField(
            model_name='pds',
            name='PDS_Note',
            field=models.TextField(default=None, verbose_name='PDS_Note'),
        ),
        migrations.AlterField(
            model_name='mds',
            name='E_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mds02.EQT', verbose_name='EQT_No'),
        ),
        migrations.AlterField(
            model_name='mds',
            name='M_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mds02.MR', verbose_name='MR_No'),
        ),
        migrations.AlterField(
            model_name='mds',
            name='P_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mds02.PJT', verbose_name='PJT_No'),
        ),
        migrations.AlterField(
            model_name='mr',
            name='M_Name',
            field=models.CharField(max_length=50, verbose_name='MR_No'),
        ),
        migrations.AlterField(
            model_name='mr',
            name='P_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mds02.PJT', verbose_name='PJT_No'),
        ),
        migrations.AlterField(
            model_name='pds',
            name='E_Name',
            field=models.CharField(max_length=40, verbose_name='EQT_Name'),
        ),
        migrations.AlterField(
            model_name='pds',
            name='E_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mds02.EQT', verbose_name='EQT_No'),
        ),
        migrations.AlterField(
            model_name='pds',
            name='M_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mds02.MR', verbose_name='MR_No'),
        ),
        migrations.AlterField(
            model_name='pds',
            name='PD_Dens',
            field=models.IntegerField(verbose_name='Density'),
        ),
        migrations.AlterField(
            model_name='pds',
            name='PD_Fluid',
            field=models.CharField(max_length=20, verbose_name='Fluid'),
        ),
        migrations.AlterField(
            model_name='pds',
            name='PD_Head',
            field=models.IntegerField(verbose_name='Head'),
        ),
        migrations.AlterField(
            model_name='pds',
            name='PD_NPSH',
            field=models.IntegerField(verbose_name='NPSH'),
        ),
        migrations.AlterField(
            model_name='pds',
            name='P_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mds02.PJT', verbose_name='PJT_No'),
        ),
    ]
