# Generated by Django 3.0.3 on 2020-03-12 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mds02', '0006_auto_20200311_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqt',
            name='E_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
