# Generated by Django 2.0.13 on 2020-03-24 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mds02', '0007_eqt_e_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqt',
            name='E_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
    ]
