# Generated by Django 3.0.3 on 2020-02-24 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mds', '0002_mr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mr',
            name='PJT_Client',
        ),
    ]
